# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do

    sh("bash", "./configsentry.sh")
    
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    increment_build_number(
        build_number: latest_testflight_build_number + 1,
        xcodeproj: "Runner.xcodeproj"
    )
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    # remove temp file
    sh("mv ../../lib/main.dart-e ../../lib/main.dart")
    
    sentry_upload_dif(
        auth_token: ENV['SENTRY_AUTH_TOKEN'],
        org_slug: 'mmmediacom',
        project_slug: 'despresso',
        include_sources: true, # Optional. For source context.
    )

    upload_to_testflight


  end
  
  lane :betamatch do
    # disable_automatic_code_signing(path: "Runner.xcodeproj")
    update_code_signing_settings(
        use_automatic_signing: false,
        path: "Runner.xcodeproj"
    )


    setup_ci

    # match(
    #     type: "development",
    #     readonly: is_ci,
    #     # keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
    #     # keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
    #     username: 'obiwan007',
    #     git_user_email: 'markus.miertschink@hotmail.com',
    #   )

    match(
        type: "appstore",
        readonly: is_ci,
        # keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
        # keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
        username: 'obiwan007',
        git_user_email: 'markus.miertschink@hotmail.com',
      )

    # update_project_provisioning(
    #     xcodeproj: "Runner.xcodeproj",
    # )
   
    # get_certificates           # invokes cert
    # get_provisioning_profile   # invokes sigh
    app_store_connect_api_key(
        key_id: ENV["API_KEY_ID"],
        issuer_id: ENV["ISSUER_ID"],
        key_content: ENV["API_KEY"]
    )
    increment_build_number(
        # api_key: lane_context[SharedValues::APP_STORE_CONNECT_API_KEY],
        build_number: latest_testflight_build_number + 1,
        xcodeproj: "Runner.xcodeproj"
    )

    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")    

    upload_to_testflight(skip_waiting_for_build_processing: false, api_key:  lane_context[SharedValues::APP_STORE_CONNECT_API_KEY])
  end
end
