name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  # push:
  #   branches:
  #     - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:  
  buildall:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: ${{ runner.tool_cache }}/flutter
          key: deps-${{ hashFiles('**/pubspec.lock') }}

      - name: Decode secrets.properties file
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
        run: echo "$KEYSTORE" | base64 -d > android/upload-keystore.jks

      - name: bash
        env:
          KEYPROPERTIES: ${{ secrets.KEYPROPERTIES }}
        run: echo "$KEYPROPERTIES" > android/key.properties        

      - run: ls -l android

      - name: JavaSetup
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'          
          check-latest: true

      - name: InstallFlutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
          architecture: x64 # optional, x64 or arm64

      - name: Version
        run: flutter --version

      - name: Update pods
        run: pod repo update

      - name: Build iOS  
        run: flutter build ios --release --no-codesign

      - name: Build APK  
        run: flutter build appbundle

      - name: Upload Android app
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Android
          path:  build/app/outputs/bundle/release/*
